services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn hotel_project.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: bitnami/postgresql:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./.env.db

  nginx:
    image: nginx:1
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/static
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  postgres_data:
